
name: mobile_arquitetura_01
description: Projeto Flutter com arquitetura em camadas usando Provider e DummyJSON API
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  flutter_bloc: ^8.1.3
  http: ^0.13.6

flutter:
  uses-material-design: true
